/**
 * VDMS
 * vDMS Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface PartRequest {
    

    /**
     * Checks online master for PNC of part if enabled, defaults to false
     */
    checkOLM?: boolean;

    /**
     * Checks Parts Master when set to true, defaults to false
     */
    checkPartMaster?: boolean;

    /**
     * Customer record's DMS id
     */
    customerNumber?: string;

    /**
     * Labor type of part
     */
    laborType?: string;

    /**
     * Additional formula for determining price/manufacturing details of a part
     */
    lookupSource?: string;

    /**
     * OEM code
     */
    makeCode?: string;

    /**
     * Part identifier to lookup
     */
    partId?: string;

    /**
     * Used to override default sale type of customer record
     */
    partSaleType?: string;
}
