/**
 * VDMS
 * vDMS Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface Vehicle {
    

    /**
     * Vehicle color maxLength = 128
     */
    color?: string;

    /**
     * List of vehicle comments
     */
    comments?: Array<models.Comment>;

    /**
     * Customer's DMS ID maxLength = 128
     */
    custExtId?: string;

    /**
     * Delivery date of vehicle to customer in milliseconds
     */
    deliveryDate?: number;

    /**
     * DMS vehicle identifier maxLength = 128
     */
    extId?: string;

    /**
     * Date of vehicles last service in milliseconds
     */
    lastServiceDate?: number;

    /**
     * Vehicle license plate maxLength = 128
     */
    license?: string;

    /**
     * Vehicle make maxLength = 128
     */
    make?: string;

    /**
     * Mileage of vehicle maxLength = 64
     */
    mileage?: number;

    /**
     * Date when vehicle's milesage was last updated in milliseconds
     */
    mileageDate?: number;

    /**
     * Vehicle model maxLength = 128
     */
    model?: string;

    /**
     * Vehicle year maxLength = 64
     */
    modelYear?: number;

    /**
     * DMS Id for sales person of vehicle maxLength = 128
     */
    salesPersonId?: string;

    /**
     * Selling Company Code maxLength = 128
     */
    sellingCompany?: string;

    /**
     * internal Selling Dealer Code maxLength = 128
     */
    sellingDealerCode?: string;

    /**
     * Dealer assigned stock number maxLength = 128
     */
    stockNumber?: string;

    /**
     * Xtime vehicle identifier maxLength = 64
     */
    vehicleId?: number;

    /**
     * Vehicle's VIN maxLength = 17
     */
    vin?: string;
}
